### PR TITLE
Upgrade solarium library to 5.0

### PR DESCRIPTION
**Pull request by ipf**
* Add support for Solr 8
* Drop support for PHP < 7.1

### CODE REVIEW

**Comment by ipf** [comment]
Requiring PHP 7.1 and above may clash with the TYPO3 8.7 [requirements](https://docs.typo3.org/typo3cms/InstallationGuide/8.7/In-depth/SystemRequirements/Index.html) for PHP, as PHP 7.x is supported, and *find* still supports TYPO3 8.7.

**Comment by mh-goe** [comment]
From my perspective it is important to completely support TYPO3 v8 even at the cost of not being able to provide support for Solr 8. 

Therefore it would be very useful to use git tags for version management. This way we could preserve the current find-version, compatibility and TYPO3 support for version 8.7.x in a seperate tag while continuing the extension development for higher versions of TYPO3 and Solarium requiring higher PHP versions in another tag. 

To not lose any users in this kind of transitional phase it might be advisable to keep the master branch even with the latest tag for TYPO3 8.7 support until the support for priority bugfixes in TYPO3 v8 terminates on Mar, 31 2020. From that day on the master branch would be even with the absolutely latest commit to a dev tag. 

Furthermore to keep users informed about the requirements of the respective find-version the README.md should contain a shield at the beginning providing information on the supported TYPO3 version and maybe the required PHP version, for instance https://img.shields.io/badge/TYPO3-8.7.x-yellow.svg and https://img.shields.io/badge/php-7.1-blue.svg.

**Comment by ssp** [comment]
@ipf personally I like new Solr versions and dislike old PHP versions … but then again I don’t have legacy users I need to support.

**Comment by ipf** [comment]
Not needed because of #161

**Pull request closed without merging**
